title: "Dillon Shearer"
description: "Data Analyst || Scientist"
url: "https://dillon-shearer.github.io"
social_links:
  - https://www.linkedin.com/in/dillonshearer/
  - https://github.com/dillon-shearer
theme: jekyll-theme-minimal
